const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const C={scooter:{Xiaomi:["Electric Scooter 4","Electric Scooter 4 Pro (2nd Gen)","Electric Scooter 4 Lite","Electric Scooter 5","Electric Scooter 5 Pro","Electric Scooter 5 Max","Electric Scooter 5 Elite","4 Ultra"],"Segway-Ninebot":["MAX G2","F2 Pro","G2D","GT2"],NIU:["KQi2 Pro","KQi3 Pro","KQi Air"],Navee:["V50","V40 Pro","ST3","ST3 Pro"]},bike:{Bosch:["Smart System"]}};
let transport="",type="",brand="",model="",step=0,timer=null;
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
function log(x){$('#log').textContent+=`[${new Date().toLocaleTimeString()}] ${x}\n`}
$$('[data-transport]').forEach(b=>b.onclick=()=>{transport=b.dataset.transport;$('#status').textContent=transport;show('vehicle');log('Verbindung: '+transport)});
$$('[data-type]').forEach(b=>b.onclick=()=>{type=b.dataset.type;$('#brands').innerHTML='';Object.keys(C[type]).forEach(k=>{const x=document.createElement('button');x.className='tile';x.innerHTML=`<b>${k}</b><small>${C[type][k].length} Modelle</small>`;x.onclick=()=>{brand=k;$('#models').innerHTML='';C[type][k].forEach(m=>{const y=document.createElement('button');y.className='tile';y.innerHTML=`<b>${m}</b><small>Auswählen</small>`;y.onclick=()=>{model=m;$('#title').textContent=m;$('#subtitle').textContent=`${brand} · ${transport}`;show('dashboard');log('Modell: '+brand+' '+model)};$('#models').append(y)});show('model')};$('#brands').append(x)});show('brand')});
$$('.back').forEach(b=>b.onclick=()=>{const s=$('.screen.active').id;show(s==='dashboard'?'model':s==='model'?'brand':s==='brand'?'vehicle':'transport')});
$('#connect').onclick=async()=>{try{if(transport==='Bluetooth'&&navigator.bluetooth){const d=await navigator.bluetooth.requestDevice({acceptAllDevices:true});$('#conn').textContent='BLE: '+(d.name||'Unbekannt');log('BLE-Gerät ausgewählt')}else if(transport==='Kabel'&&navigator.serial){await navigator.serial.requestPort();$('#conn').textContent='USB-Serial ausgewählt';log('Serial-Port ausgewählt')}else log('Web Bluetooth/Web Serial in diesem Browser nicht verfügbar.')}catch(e){log('Verbindung: '+e.message)}};
$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;const h=await crypto.subtle.digest('SHA-256',await f.arrayBuffer());const sha=[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');$('#info').textContent=`${f.name}\n${f.size.toLocaleString('de-DE')} Bytes\nSHA-256: ${sha}`;log('Firmware-Datei gehasht')};
const W={police:[["🚓 Police Mode","Der Modus setzt das lokale Profil auf Original/Kontrolle. Er ist kein Umgehungsmodus."],["🔒 Änderungen gesperrt","Profiländerungen werden in dieser Oberfläche gesperrt."],["📋 Prüfen","Kontrolliere Modell, Verbindung und Firmwareinformationen."],["✅ Aktivieren","Police Mode wird lokal aktiviert."]],reset:[["⚠️ Original wiederherstellen","Nur eine verifizierte Original-Firmware für exakt dieses Gerät darf verwendet werden."],["💾 Backup","Ohne verifiziertes Backup nicht fortfahren."],["🔌 Verbindung","Stabile Stromversorgung und Verbindung sicherstellen."],["🛑 Letzte Kontrolle","Diese Release führt keinen eigentlichen Firmware-Flash aus."]],flash:[["⚠️ Achtung","Ein Firmware-Flash kann Geräte beschädigen."],["🏁 Einsatzbereich","Bestätige den rechtlich zulässigen Einsatzbereich. Die Software macht nichts automatisch legal."],["🔋 Strom & Verbindung","Nur verifizierte Firmware und passende Hardware verwenden."],["🛑 Letzte Kontrolle","Diese Safe Release aktiviert keinen Leistungs-/Geschwindigkeits-Flash."]]};
function openWizard(kind){step=0;$('#modal').dataset.kind=kind;$('#modal').classList.remove('hidden');renderWizard()}
function renderWizard(){const a=W[$('#modal').dataset.kind][step];$('#mstep').textContent=`SICHERHEIT ${step+1}/4`;$('#mcontent').innerHTML=`<h2>${a[0]}</h2><p>${a[1]}</p>`;$('#ack').checked=false;$('#mnext').disabled=true;$('#ack').onchange=e=>$('#mnext').disabled=!e.target.checked;let n=3;$('#countdown').textContent=`Bitte ${n} Sekunden warten…`;clearInterval(timer);timer=setInterval(()=>{n--;$('#countdown').textContent=n>0?`Bitte ${n} Sekunden warten…`:'Bereit';if(n<=0){clearInterval(timer);$('#mnext').disabled=!$('#ack').checked}},1000)}
$('#mnext').onclick=()=>{if(step<3){step++;renderWizard();return}const k=$('#modal').dataset.kind;clearInterval(timer);$('#modal').classList.add('hidden');if(k==='police'){$('#profile').textContent='🚓 POLICE MODE · ORIGINAL';log('Police Mode aktiviert')}if(k==='reset'){$('#profile').textContent='↩ ORIGINAL / RESET VORBEREITET';log('Original-Wiederherstellung vorbereitet')}if(k==='flash')log('Flash nicht aktiviert: Safe Release')};
$('#mback').onclick=()=>{if(step){step--;renderWizard()}else{$('#modal').classList.add('hidden');clearInterval(timer)}};$('#mclose').onclick=()=>{$('#modal').classList.add('hidden');clearInterval(timer)};$('#police').onclick=()=>openWizard('police');$('#reset').onclick=()=>openWizard('reset');$('#prepare').onclick=()=>openWizard('flash');
